### ISSUE TITLE
项目描述建议

### ISSUE THREAD

**Issue by cnk700i** [meishild/hass-custom-components#1]
你好，我看这个项目是基于[我的项目](https://github.com/cnk700i/ha_modified_components/tree/master/hf_weather)修改而来，希望能在描述里能把参考来源写出来。另外最好能标注清楚功能说明，能区分原项目功能以及新项目新增的功能~

**Comment by meishild** [comment]
好的，我这个整合了所以没法fork

**Comment by meishild** [comment]
我修了两个前端的bug增加了uv你可以合并过去@cnk700i
